#!/usr/bin/env python3
import subprocess
from subprocess import Popen
import sys

#mapFiles is a list of files to read character definitions from
mapFiles = ["maps/Greek"]

#keymaps is a dictionary of name:character combinations, to be populated from
#mapFiles
keymaps = {}

#Read all the map files and put them into keymaps dictionary
for fname in mapFiles:
    for line in open(fname):
        #Strip trailing whitespace (esp newline), then check for blank lines or
        #comment lines
        line = line.rstrip()
        if line=='' or line[0]=='#':
            continue
        char,name = line.split(maxsplit=1)
        keymaps[name] = char

#Use dmenu to choose a character
dmenuProcess = Popen("dmenu", stdin=subprocess.PIPE,stdout=subprocess.PIPE,
    stderr=sys.stderr, shell=True,bufsize=1,universal_newlines=True)

for char in keymaps.keys(): dmenuProcess.stdin.write(char+'\n')
selection,_ = dmenuProcess.communicate()
selection = selection.rstrip()

#Only continue if this was a valid selection
if selection in keymaps:
    selectedChar = keymaps[selection]
    xdoProcess = Popen('xdotool type '+selectedChar,shell=True)
    xdoProcess.wait()
